-- Insert Guests
INSERT INTO guests (first_name, last_name, email_address, phone_number, address, country, state) VALUES
                                                                                                     ('John', 'Doe', 'john.doe@example.com', '123-456-7890', '123 Main St', 'USA', 'CA'),
                                                                                                     ('Jane', 'Smith', 'jane.smith@example.com', '123-456-7891', '456 Oak St', 'USA', 'NY'),
                                                                                                     ('Jim', 'Brown', 'jim.brown@example.com', '123-456-7892', '789 Pine St', 'USA', 'TX'),
                                                                                                     ('Lucy', 'Johnson', 'lucy.johnson@example.com', '123-456-7893', '321 Maple St', 'USA', 'FL'),
                                                                                                     ('Mike', 'Williams', 'mike.williams@example.com', '123-456-7894', '654 Elm St', 'USA', 'IL'),
                                                                                                     ('Anna', 'Taylor', 'anna.taylor@example.com', '123-456-7895', '789 Birch St', 'USA', 'WA'),
                                                                                                     ('Mark', 'Anderson', 'mark.anderson@example.com', '123-456-7896', '321 Cedar St', 'USA', 'OR'),
                                                                                                     ('Paul', 'Thomas', 'paul.thomas@example.com', '123-456-7897', '654 Pine St', 'USA', 'NV'),
                                                                                                     ('Emily', 'Harris', 'emily.harris@example.com', '123-456-7898', '987 Oak St', 'USA', 'AZ'),
                                                                                                     ('Laura', 'Clark', 'laura.clark@example.com', '123-456-7899', '123 Maple St', 'USA', 'NM'),
                                                                                                     ('Kevin', 'Lewis', 'kevin.lewis@example.com', '123-456-7810', '456 Birch St', 'USA', 'CO'),
                                                                                                     ('Sophia', 'Walker', 'sophia.walker@example.com', '123-456-7811', '789 Cedar St', 'USA', 'UT'),
                                                                                                     ('James', 'Hall', 'james.hall@example.com', '123-456-7812', '321 Oak St', 'USA', 'ID'),
                                                                                                     ('Oliver', 'Young', 'oliver.young@example.com', '123-456-7813', '654 Maple St', 'USA', 'MT'),
                                                                                                     ('Mia', 'King', 'mia.king@example.com', '123-456-7814', '987 Birch St', 'USA', 'WY'),
                                                                                                     ('David', 'Wright', 'david.wright@example.com', '123-456-7815', '123 Cedar St', 'USA', 'ND'),
                                                                                                     ('Daniel', 'Lopez', 'daniel.lopez@example.com', '123-456-7816', '456 Pine St', 'USA', 'SD'),
                                                                                                     ('Liam', 'Hill', 'liam.hill@example.com', '123-456-7817', '789 Oak St', 'USA', 'NE'),
                                                                                                     ('Ava', 'Scott', 'ava.scott@example.com', '123-456-7818', '321 Maple St', 'USA', 'KS'),
                                                                                                     ('Isabella', 'Green', 'isabella.green@example.com', '123-456-7819', '654 Birch St', 'USA', 'OK'),
                                                                                                     ('Elijah', 'Adams', 'elijah.adams@example.com', '123-456-7820', '987 Cedar St', 'USA', 'LA'),
                                                                                                     ('Lucas', 'Baker', 'lucas.baker@example.com', '123-456-7821', '123 Pine St', 'USA', 'AR'),
                                                                                                     ('Mason', 'Gonzalez', 'mason.gonzalez@example.com', '123-456-7822', '456 Oak St', 'USA', 'MS'),
                                                                                                     ('Ethan', 'Nelson', 'ethan.nelson@example.com', '123-456-7823', '789 Maple St', 'USA', 'AL'),
                                                                                                     ('Charlotte', 'Carter', 'charlotte.carter@example.com', '123-456-7824', '321 Birch St', 'USA', 'TN'),
                                                                                                     ('Amelia', 'Mitchell', 'amelia.mitchell@example.com', '123-456-7825', '654 Cedar St', 'USA', 'KY'),
                                                                                                     ('Harper', 'Perez', 'harper.perez@example.com', '123-456-7826', '987 Pine St', 'USA', 'WV'),
                                                                                                     ('Evelyn', 'Roberts', 'evelyn.roberts@example.com', '123-456-7827', '123 Oak St', 'USA', 'DE'),
                                                                                                     ('Abigail', 'Turner', 'abigail.turner@example.com', '123-456-7828', '456 Maple St', 'USA', 'MD'),
                                                                                                     ('Avery', 'Phillips', 'avery.phillips@example.com', '123-456-7829', '789 Birch St', 'USA', 'DC');

-- Insert Rooms
INSERT INTO rooms (name, room_number, bed_info) VALUES
                                                    ('Deluxe Room', '101', 'King Bed'),
                                                    ('Standard Room', '102', 'Queen Bed'),
                                                    ('Suite', '103', 'King Bed'),
                                                    ('Single Room', '104', 'Single Bed'),
                                                    ('Double Room', '105', 'Double Bed'),
                                                    ('Family Room', '106', 'Queen Bed'),
                                                    ('Business Suite', '107', 'King Bed'),
                                                    ('Honeymoon Suite', '108', 'King Bed'),
                                                    ('Presidential Suite', '109', 'King Bed'),
                                                    ('Economy Room', '110', 'Single Bed'),
                                                    ('Superior Room', '111', 'Queen Bed'),
                                                    ('Junior Suite', '112', 'Queen Bed'),
                                                    ('Luxury Suite', '113', 'King Bed'),
                                                    ('Penthouse', '114', 'King Bed'),
                                                    ('Royal Suite', '115', 'King Bed'),
                                                    ('Comfort Room', '116', 'Queen Bed'),
                                                    ('Classic Room', '117', 'Double Bed'),
                                                    ('Premier Room', '118', 'Queen Bed'),
                                                    ('Executive Suite', '119', 'King Bed'),
                                                    ('Deluxe Suite', '120', 'King Bed'),
                                                    ('Superior Suite', '121', 'King Bed'),
                                                    ('King Room', '122', 'King Bed'),
                                                    ('Queen Room', '123', 'Queen Bed'),
                                                    ('Double Room', '124', 'Double Bed'),
                                                    ('Twin Room', '125', 'Two Single Beds'),
                                                    ('Triple Room', '126', 'Three Single Beds'),
                                                    ('Quad Room', '127', 'Four Single Beds'),
                                                    ('Family Suite', '128', 'Queen Bed'),
                                                    ('Grand Suite', '129', 'King Bed'),
                                                    ('Luxury Room', '130', 'Queen Bed'),
                                                    ('Presidential Room', '131', 'King Bed'),
                                                    ('Junior Room', '132', 'Double Bed'),
                                                    ('Single Deluxe', '133', 'Single Bed'),
                                                    ('Double Deluxe', '134', 'Double Bed'),
                                                    ('Economy Suite', '135', 'Queen Bed'),
                                                    ('Standard Suite', '136', 'King Bed'),
                                                    ('Superior Deluxe', '137', 'Queen Bed'),
                                                    ('Deluxe King', '138', 'King Bed'),
                                                    ('Premium Room', '139', 'Queen Bed'),
                                                    ('Classic Suite', '140', 'King Bed'),
                                                    ('Luxury King', '141', 'King Bed'),
                                                    ('Grand Deluxe', '142', 'King Bed'),
                                                    ('Royal Deluxe', '143', 'King Bed'),
                                                    ('Presidential Deluxe', '144', 'King Bed'),
                                                    ('Executive Room', '145', 'Queen Bed'),
                                                    ('Premier Suite', '146', 'King Bed'),
                                                    ('Economy King', '147', 'King Bed'),
                                                    ('Family Deluxe', '148', 'Queen Bed'),
                                                    ('Grand Room', '149', 'King Bed'),
                                                    ('Classic Deluxe', '150', 'Queen Bed');

-- Insert Reservations
INSERT INTO reservations (room_id, guest_id, reservation_date) VALUES
-- Reservations for previous days
(1, 1, DATEADD('DAY', -15, CURRENT_DATE)),
(2, 2, DATEADD('DAY', -14, CURRENT_DATE)),
(3, 3, DATEADD('DAY', -13, CURRENT_DATE)),
(4, 4, DATEADD('DAY', -12, CURRENT_DATE)),
(5, 5, DATEADD('DAY', -11, CURRENT_DATE)),
(6, 6, DATEADD('DAY', -10, CURRENT_DATE)),
(7, 7, DATEADD('DAY', -9, CURRENT_DATE)),
(8, 8, DATEADD('DAY', -8, CURRENT_DATE)),
(9, 9, DATEADD('DAY', -7, CURRENT_DATE)),
(10, 10, DATEADD('DAY', -6, CURRENT_DATE)),
(11, 11, DATEADD('DAY', -5, CURRENT_DATE)),
(12, 12, DATEADD('DAY', -4, CURRENT_DATE)),
(13, 13, DATEADD('DAY', -3, CURRENT_DATE)),
(14, 14, DATEADD('DAY', -2, CURRENT_DATE)),
(15, 15, DATEADD('DAY', -1, CURRENT_DATE)),
-- Reservations for today
(16, 16, CURRENT_DATE),
(17, 17, CURRENT_DATE),
(18, 18, CURRENT_DATE),
(19, 19, CURRENT_DATE),
(20, 20, CURRENT_DATE),
(21, 21, CURRENT_DATE),
(22, 22, CURRENT_DATE),
(23, 23, CURRENT_DATE),
(24, 24, CURRENT_DATE),
(25, 25, CURRENT_DATE),
(26, 26, CURRENT_DATE),
(27, 27, CURRENT_DATE),
(28, 28, CURRENT_DATE),
(29, 29, CURRENT_DATE),
(30, 30, CURRENT_DATE);
